# Generated by Django 5.0.7 on 2024-08-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_user_is_author_user_special_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=True, verbose_name='وضعیت نویسندگی'),
        ),
    ]
