# Generated by Django 5.0.7 on 2024-07-30 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name=' آیا نمایش داده شود؟ ')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پست')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')),
                ('excerpt', models.TextField(max_length=100, verbose_name=' پست چکیده مطالب')),
                ('description', models.TextField(verbose_name='متن پست')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('photo', models.ImageField(upload_to='media', verbose_name='عکس مقاله')),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس')], max_length=10, verbose_name='وضعیت انتشار ')),
                ('category', models.ManyToManyField(to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
