# Generated by Django 5.0.7 on 2024-08-03 10:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name=' پست ویژه '),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن پست'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت انتشار '),
        ),
    ]
